<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta name="description" content="Tsung is a distributed load testing tool" />
    <meta name="keywords" content="Tsung, performance, load, testing, HTTP, jabber" />
    <meta name="robots" content="index,follow" />
    <link rel="stylesheet" type="text/css" href="style/tsung.css" />
    <title>Tsung main page</title>
</head>

<body>
<div id="container">
<div id="header">
  <h1><a href="http://tsung.erlang-projects.org/">Tsung</a></h1>
  <h2>Performance Test Results</h2>
</div>

<div id="main">
<h2 class="index"> Statistics</h2>
<p><a href="report.html">Statistics Report</a></p>
<!-- Removido link ts_web:status que não funciona em viewer estático -->
</div>

<div id="footer">
  <p>
    <img id="bottom" src="http://tsung.erlang-projects.org/images/ts-small.png" alt="tsung logo" /> 
    Generated by <em>Tsung</em> version 1.8.0, the multi-protocol distributed load testing tool.
  </p>
</div>

</div>
</body>
</html>